/**
 * `explain <ID>` registry and the generator behind `docs/interpretations.md`.
 *
 * Every ID the CLI can explain comes from metadata that the code itself
 * uses: interpretation `META` (I1 … I8), direction rules (`D-…`),
 * not-interpreted items (`N-…`), verdict categories and flags. Nothing
 * here is hand-duplicated; `scripts/render-interpretations.mjs` writes
 * `renderInterpretationsDoc()` to disk and a test keeps the file current.
 */

import { CATEGORY_META, DEFAULT_FAILING_CATEGORIES, PROJECTED_PSEUDO_CATEGORY } from "./categories.js";
import { DIRECTION_RULES } from "./direction.js";
import { FLAG_META, INTERPRETATIONS, INTERPRETATIONS_DATE, NOT_INTERPRETED } from "./interpretations/index.js";

export type ExplainKind = "interpretation" | "direction-rule" | "not-interpreted" | "category" | "flag";

export interface ExplainEntry {
  id: string;
  kind: ExplainKind;
  title: string;
  /** `label: value` lines shown under the title. */
  facts: Array<[string, string]>;
  explain: string;
}

/** Every explainable entry, in documentation order. */
export function explainEntries(): ExplainEntry[] {
  const entries: ExplainEntry[] = [];
  for (const { META } of INTERPRETATIONS) {
    entries.push({
      id: META.id,
      kind: "interpretation",
      title: META.title,
      facts: [
        ["tier", META.tier],
        ["doc section", META.doc_section],
        ["semantics doc date", META.semantics_doc_date],
        ["summary", META.summary],
      ],
      explain: META.explain,
    });
  }
  for (const item of NOT_INTERPRETED) {
    entries.push({
      id: item.id,
      kind: "not-interpreted",
      title: item.title,
      facts: [
        ["tier", "unresolved"],
        ["detected", item.detect === undefined ? "no (files not read in V0)" : "yes"],
        ["semantics doc date", INTERPRETATIONS_DATE],
      ],
      explain: item.explain,
    });
  }
  for (const rule of DIRECTION_RULES) {
    entries.push({
      id: rule.id,
      kind: "direction-rule",
      title: rule.title,
      facts: [
        ["direction", rule.direction],
        ["tier", rule.tier],
      ],
      explain: rule.explain,
    });
  }
  for (const category of CATEGORY_META) {
    entries.push({
      id: category.id,
      kind: "category",
      title: category.title,
      facts: [["fails by default", category.failing_by_default ? "yes" : "no (annotate-only)"]],
      explain: category.explain,
    });
  }
  entries.push({
    id: PROJECTED_PSEUDO_CATEGORY,
    kind: "category",
    title: "Pseudo-category: projected widenings fail",
    facts: [["fails by default", "no"]],
    explain:
      "Naming projected in --fail-on makes every widening delta whose direction or breadth claim is projected exit 1. Naming only projected keeps the default failing categories; naming it with other categories restricts the failing set to those categories plus projected widenings.",
  });
  for (const flag of FLAG_META) {
    entries.push({ id: flag.id, kind: "flag", title: `flag ${flag.id}`, facts: [], explain: flag.explain });
  }
  return entries;
}

/** All valid `explain` IDs, in documentation order. */
export function explainIds(): string[] {
  return explainEntries().map((entry) => entry.id);
}

/** Look up one explainable ID (exact match). */
export function explain(id: string): ExplainEntry | null {
  return explainEntries().find((entry) => entry.id === id) ?? null;
}

/** Text shown by `agent-surface explain <ID>`. */
export function renderExplain(entry: ExplainEntry): string {
  const lines = [`${entry.id}  ${entry.title}`, `  kind: ${entry.kind}`];
  for (const [label, value] of entry.facts) {
    lines.push(`  ${label}: ${value}`);
  }
  lines.push("", `  ${entry.explain}`, "");
  return `${lines.join("\n")}\n`;
}

function table(header: string[], rows: string[][]): string[] {
  const escape = (cell: string): string => cell.replace(/\|/g, "\\|");
  return [
    `| ${header.join(" | ")} |`,
    `| ${header.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(escape).join(" | ")} |`),
  ];
}

/** Markdown for `docs/interpretations.md`, generated from the metadata above. */
export function renderInterpretationsDoc(): string {
  const out: string[] = [];
  out.push(
    "<!-- Generated by scripts/render-interpretations.mjs from src/interpretations/*.ts, src/direction.ts and src/categories.ts. Do not edit by hand; a test compares this file with the generator's output. -->",
    "",
    "# Interpretations, direction rules and verdict categories",
    "",
    `Closed list, dated **${INTERPRETATIONS_DATE}** (the \`semantics_doc_date\` every snapshot and diff carries). Every entry below is printed by \`agent-surface explain <ID>\`. Anything outside the interpretation list is reported as \`unresolved\` and never rendered as clean.`,
    "",
    "## Interpretations (§3.6)",
    "",
    ...table(
      ["ID", "Interpretation", "Tier", "Claude Code doc section"],
      INTERPRETATIONS.map(({ META }) => [META.id, META.title, META.tier, META.doc_section]),
    ),
    "",
  );
  for (const { META } of INTERPRETATIONS) {
    out.push(`### ${META.id} — ${META.title}`, "", `- Tier: ${META.tier}`, `- Doc section: ${META.doc_section}`, `- Semantics doc date: ${META.semantics_doc_date}`, `- Summary: ${META.summary}`, "", META.explain, "");
  }
  out.push("## Explicitly not interpreted", "", "Each item yields `unresolved` with a note naming it when it can be observed in a V0 input; items marked *not observable* concern files V0 never reads.", "");
  for (const item of NOT_INTERPRETED) {
    out.push(`### ${item.id} — ${item.title}${item.detect === undefined ? " (not observable in V0)" : ""}`, "", item.explain, "");
  }
  out.push(
    "## Direction rules (JG-153)",
    "",
    ...table(
      ["ID", "Delta", "Direction", "Tier"],
      DIRECTION_RULES.map((rule) => [rule.id, rule.title, rule.direction, rule.tier]),
    ),
    "",
  );
  for (const rule of DIRECTION_RULES) {
    out.push(`### ${rule.id} — ${rule.title}`, "", rule.explain, "");
  }
  out.push(
    "## Verdict categories (JG-155)",
    "",
    `Default failing categories: ${DEFAULT_FAILING_CATEGORIES.map((id) => `\`${id}\``).join(", ")}. \`--fail-on <a,b,…>\` replaces that set; \`${PROJECTED_PSEUDO_CATEGORY}\` may be added to fail on projected widenings as well.`,
    "",
    ...table(
      ["Category", "Meaning", "Fails by default"],
      CATEGORY_META.map((category) => [category.id, category.title, category.failing_by_default ? "yes" : "no"]),
    ),
    "",
  );
  for (const category of CATEGORY_META) {
    out.push(`### ${category.id} — ${category.title}`, "", category.explain, "");
  }
  out.push("## Flags", "", ...table(["Flag", "Meaning"], FLAG_META.map((flag) => [flag.id, flag.explain])), "");
  out.push(
    "## Exit codes",
    "",
    "| Code | Meaning |",
    "| --- | --- |",
    "| 0 | no change, or narrowing / neutral / annotate-only changes |",
    "| 1 | proven expansion in a failing category; projected widening with `--fail-on projected`; undecided delta with `--strict` |",
    "| 2 | undecided deltas only (tier not proven, or breadth unresolved): pass with annotation |",
    "| 3 | scan incomplete (unparseable input, duplicate keys, missing ref); always wins, expansions are still printed |",
    "| 64 | usage error |",
    "",
  );
  return `${out.join("\n")}\n`;
}
