version: 2
updates:
  - package-ecosystem: cargo
    directory: /kit-board/companion
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      companion-dependencies:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
