//! The v1/v2 parity gate (section 2.7): the companion's scan over
//! `tests/fixtures/usage-v2/parity/` must produce the bucket rows, session
//! hashes, event digests, allowance slots, and coverage counters that
//! `collect.py` v1.1.0 produced (`expected.json`, generated by
//! `companion/scripts/fixtures.py expected`).

use std::path::PathBuf;
use std::str::FromStr;
use std::time::Duration;

use jiff::Timestamp;
use observatory_adapters::jsonl::scan;
use observatory_adapters::readings::ingest_statusline_inbox;
use observatory_contract::{AccountId, CollectionSettings, Provider, Uuid};
use observatory_core::adapter::{BindingContext, IdentityState, RunContext};
use observatory_core::outbox::{bucket_digest, bucket_key};
use observatory_core::pyjson::digest;
use observatory_core::state::State;
use serde_json::{Value, json};

fn corpus() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../tests/fixtures/usage-v2/parity")
}

fn expected() -> Value {
    let path = corpus().join("expected.json");
    serde_json::from_slice(&std::fs::read(&path).unwrap_or_else(|_| panic!("missing {}", path.display())))
        .unwrap()
}

struct Harness {
    _dir: tempfile::TempDir,
    state: State,
    ctx: RunContext,
    binding: BindingContext,
}

fn harness(provider: Provider, roots: Vec<PathBuf>, account: &str, since: &str) -> Harness {
    let dir = tempfile::tempdir().unwrap();
    let state_path = dir.path().join("state.sqlite3");
    let state = State::open(&state_path).unwrap();
    let binding = BindingContext {
        binding_id: Uuid::from_str("11111111-1111-4111-8111-111111111111").unwrap(),
        account_id: AccountId::from_str(account).unwrap(),
        provider,
        enabled: true,
        identity_hash: None,
        identity: IdentityState::Confirmed,
        roots,
        codex_home: None,
        cursor_state_db: None,
    };
    let now = Timestamp::from_str("2026-09-12T00:00:00Z").unwrap();
    let ctx = RunContext::new(
        now,
        since.to_owned(),
        observatory_core::pyjson::epoch_text(&format!("{since}T00:00:00Z")).unwrap(),
        CollectionSettings::defaults(),
        0,
        None,
        vec![binding.clone()],
        vec![],
        dir.path().to_path_buf(),
        state_path,
        corpus().join("claude-statusline"),
        true,
        Duration::from_secs(60),
    );
    Harness { _dir: dir, state, ctx, binding }
}

fn bucket_values(state: &State, binding: &str) -> (Vec<Value>, Vec<Value>) {
    let rows = state.bucket_rows(binding).unwrap();
    let buckets = rows
        .iter()
        .map(|row| {
            json!({"session_hash": row.session_hash, "hour": row.hour, "model": row.model,
                "input_tokens": row.input_tokens, "cached_tokens": row.cached_tokens,
                "cache_write_tokens": row.cache_write_tokens, "output_tokens": row.output_tokens,
                "calls": row.calls, "total_tokens": row.total_tokens})
        })
        .collect();
    let digests = rows
        .iter()
        .map(|row| {
            let key = digest(&json!([row.session_hash, row.hour, row.model]));
            let scoped = bucket_key(&Uuid::from_str("11111111-1111-4111-8111-111111111111").unwrap(), row);
            assert!(scoped.ends_with(key.as_str()));
            json!({"key": key.as_str(), "hash": bucket_digest(row).as_str()})
        })
        .collect();
    (buckets, digests)
}

fn event_values(state: &State, binding: &str) -> Vec<Value> {
    let mut rows = state.events(binding).unwrap();
    rows.sort_by(|a, b| a.id.cmp(&b.id));
    rows.iter()
        .map(|row| {
            json!({"id": row.id, "session": row.session, "hour": row.hour, "model": row.model,
                "input_tokens": row.input_tokens, "cached_tokens": row.cached_tokens,
                "cache_write_tokens": row.cache_write_tokens, "output_tokens": row.output_tokens})
        })
        .collect()
}

fn quota_values(state: &State, binding: &str) -> Vec<Value> {
    let mut items: Vec<Value> = state
        .dirty_allowance_slots(binding)
        .unwrap()
        .into_iter()
        .map(|(_, payload)| {
            let mut value: Value = serde_json::from_str(&payload).unwrap();
            if let Value::Object(map) = &mut value {
                map.remove("raw_window_id");
            }
            value
        })
        .collect();
    items.sort_by(|a, b| {
        (a["window_key"].as_str(), a["observed_at"].as_str())
            .cmp(&(b["window_key"].as_str(), b["observed_at"].as_str()))
    });
    items
}

fn assert_provider(provider: Provider, roots: Vec<PathBuf>, product: &'static str, with_inbox: bool) {
    let expected = expected();
    let since = expected["since"].as_str().unwrap();
    let account = expected["accounts"][provider.as_str()].as_str().unwrap();
    let want = &expected[provider.as_str()];
    let h = harness(provider, roots, account, since);
    let binding = h.binding.binding_id.as_str().to_owned();
    let metrics = scan(&h.state, &h.ctx, &h.binding, provider, product, true).unwrap();
    let mut malformed = metrics.malformed_lines;
    if with_inbox {
        malformed += ingest_statusline_inbox(&h.state, &h.ctx, &h.binding).unwrap();
    }
    let coverage = json!({"files": metrics.files, "bytes_read": metrics.bytes_read, "malformed_lines": malformed,
        "unavailable_roots": metrics.unavailable_roots});
    assert_eq!(coverage, want["coverage"], "{provider}: coverage counters drifted from collect.py");
    let (buckets, digests) = bucket_values(&h.state, &binding);
    assert_eq!(Value::Array(buckets), want["buckets"], "{provider}: bucket rows drifted from collect.py");
    assert_eq!(
        Value::Array(digests),
        want["bucket_digests"],
        "{provider}: bucket digests drifted from collect.py"
    );
    assert_eq!(Value::Array(event_values(&h.state, &binding)), want["events"], "{provider}: events drifted");
    assert_eq!(
        Value::Array(quota_values(&h.state, &binding)),
        want["quotas"],
        "{provider}: allowance slots drifted"
    );
    assert_eq!(
        h.state.file_count(&binding).unwrap(),
        want["checkpointed_files"].as_u64().unwrap(),
        "{provider}: checkpoints"
    );

    // A second scan over unchanged files reads nothing and changes nothing.
    let again = scan(&h.state, &h.ctx, &h.binding, provider, product, true).unwrap();
    assert_eq!(again.bytes_read, 0, "{provider}: unchanged files were re-read");
    assert_eq!(again.files, metrics.files);
    let (buckets_again, _) = bucket_values(&h.state, &binding);
    assert_eq!(Value::Array(buckets_again), want["buckets"]);
}

#[test]
fn claude_execution_matches_collect_py() {
    assert_provider(Provider::Claude, vec![corpus().join("claude").join("projects")], "claude_code", true);
}

#[test]
fn codex_execution_matches_collect_py() {
    let codex = corpus().join("codex");
    assert_provider(
        Provider::Codex,
        vec![codex.join("sessions"), codex.join("archived_sessions")],
        "codex_cli",
        false,
    );
}

#[test]
fn a_missing_root_counts_as_unavailable() {
    let h = harness(
        Provider::Claude,
        vec![corpus().join("claude").join("does-not-exist")],
        "claude-primary",
        "2026-09-01",
    );
    let metrics = scan(&h.state, &h.ctx, &h.binding, Provider::Claude, "claude_code", true).unwrap();
    assert_eq!(metrics.unavailable_roots, 1);
    assert_eq!(metrics.files, 0);
}

#[test]
fn rotation_and_partial_trailing_line() {
    use std::io::Write;
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().join("logs");
    std::fs::create_dir_all(&root).unwrap();
    let file = root.join("a.jsonl");
    let record = json!({"type": "assistant", "timestamp": "2026-09-02T02:00:00Z", "sessionId": "s",
        "message": {"id": "msg-repeat", "model": "claude", "usage": {"input_tokens": 2, "cache_read_input_tokens": 20,
        "cache_creation_input_tokens": 8, "output_tokens": 10}, "content": "PRIVATE SENTINEL"}})
    .to_string();
    std::fs::write(&file, &record.as_bytes()[..40]).unwrap();
    let h = harness(Provider::Claude, vec![root.clone()], "main", "2026-09-01");
    let binding = h.binding.binding_id.as_str().to_owned();
    scan(&h.state, &h.ctx, &h.binding, Provider::Claude, "claude_code", true).unwrap();
    assert!(h.state.bucket_rows(&binding).unwrap().is_empty());
    let mut handle = std::fs::OpenOptions::new().append(true).open(&file).unwrap();
    handle.write_all(&record.as_bytes()[40..]).unwrap();
    handle.write_all(b"\n").unwrap();
    drop(handle);
    scan(&h.state, &h.ctx, &h.binding, Provider::Claude, "claude_code", true).unwrap();
    assert_eq!(h.state.bucket_rows(&binding).unwrap()[0].calls, 1);
    assert_eq!(
        scan(&h.state, &h.ctx, &h.binding, Provider::Claude, "claude_code", true).unwrap().bytes_read,
        0
    );
    std::fs::remove_file(&file).unwrap();
    std::fs::write(&file, format!("{record}\n")).unwrap();
    scan(&h.state, &h.ctx, &h.binding, Provider::Claude, "claude_code", true).unwrap();
    assert_eq!(h.state.bucket_rows(&binding).unwrap()[0].calls, 1);
    let serialized = serde_json::to_string(&h.state.bucket_rows(&binding).unwrap()[0].session_hash).unwrap();
    assert!(!serialized.contains("PRIVATE"));
}
