#!/usr/bin/env python3
"""Generate the shared usage-v2 fixture corpus and the v1 parity expectations.

    python3 scripts/fixtures.py generate   # rewrite the synthetic corpus and MANIFEST.json
    python3 scripts/fixtures.py expected   # run collect.py over the parity corpus, write expected.json
    python3 scripts/fixtures.py check      # fail unless the committed corpus and expected.json are current

Everything under kit-board/tests/fixtures/usage-v2/ is synthetic: no real account,
session, prompt, path, or credential appears. The parity corpus exercises every
rule in section 2.6 of the unified usage handoff; expected.json is what
scripts/telemetry/collect.py v1.1.0 produces from it and is the gate for the
companion's port. Python 3.10+, standard library only.
"""
from __future__ import annotations

import importlib.util
import json
import os
import shutil
import subprocess
import sys
import tempfile
import uuid
from pathlib import Path

KIT = Path(__file__).resolve().parents[2]
CORPUS = KIT / "tests" / "fixtures" / "usage-v2"
PARITY = CORPUS / "parity"
WIRE = CORPUS / "wire"
COLLECT = KIT / "scripts" / "telemetry" / "collect.py"
SINCE = "2026-09-01"
ACCOUNTS = {"claude": "claude-primary", "codex": "codex-primary"}
DECLARATION = {
    "origin": "synthetic",
    "ref": "unified-usage-handoff sections 1.7 and 2.6; generated by kit-board/companion/scripts/fixtures.py",
    "completeness": "complete",
    "excerpt_or_raw": "raw",
}

# UUID version 7 ids whose first 48 bits are the millisecond timestamps below.
SESSION_MAIN = "01a05fa1-4680-7c1e-9c9a-000000000001"  # 2026-09-02T01:00:00Z
TURN_MAIN = "01a05fa1-5a08-7000-8000-000000000002"  # 2026-09-02T01:00:05Z
SESSION_FORK = "01a05fd8-3500-7c1e-9c9a-000000000003"  # 2026-09-02T02:00:00Z
TURN_FORK_V4 = "9b0b7c1e-2b3a-4c4d-8e9f-000000000004"  # not version 7: falls back to the record timestamp


def line(obj) -> bytes:
    return (json.dumps(obj, separators=(",", ":")) + "\n").encode()


def write_lines(path: Path, lines: list[bytes], trailing_partial: bytes = b"") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(b"".join(lines) + trailing_partial)


def claude_record(at, msg_id, model, usage, session="sess-a", version="1.0.100", text="PRIVATE SENTINEL"):
    record = {"type": "assistant", "timestamp": at, "version": version, "cwd": "/private/synthetic/project",
              "message": {"id": msg_id, "model": model, "role": "assistant", "usage": usage,
                          "content": [{"type": "text", "text": text}]}}
    if session is not None:
        record["sessionId"] = session
    return record


def codex_token_count(at, total, last, rate_limits=None):
    payload = {"type": "token_count", "info": {"total_token_usage": total, "last_token_usage": last,
                                              "model_context_window": 400000}}
    if rate_limits is not None:
        payload["rate_limits"] = rate_limits
    record = {"type": "event_msg", "payload": payload}
    if at is not None:
        record["timestamp"] = at
    return record


def usage(input_tokens=0, cached=0, written=0, output=0, reasoning=0, total=None):
    return {"input_tokens": input_tokens, "cached_input_tokens": cached, "cache_write_input_tokens": written,
            "output_tokens": output, "reasoning_output_tokens": reasoning,
            "total_tokens": input_tokens + output if total is None else total}


def generate_parity() -> None:
    if PARITY.exists():
        for child in PARITY.iterdir():
            if child.name != "expected.json":
                shutil.rmtree(child) if child.is_dir() else child.unlink()
    projects = PARITY / "claude" / "projects"
    # The mirror sorts before the project and carries a smaller copy of msg_1: maxima win.
    write_lines(projects / "-Users-synthetic-mirror" / "session-a.jsonl", [
        line(claude_record("2026-09-02T02:00:00.000Z", "msg_1", "claude-opus-4-1",
                           {"input_tokens": 2, "cache_read_input_tokens": 20, "cache_creation_input_tokens": 8, "output_tokens": 5})),
    ])
    write_lines(projects / "-Users-synthetic-project" / "session-a.jsonl", [
        line(claude_record("2026-09-02T02:00:00.000Z", "msg_1", "claude-opus-4-1",
                           {"input_tokens": 2, "cache_read_input_tokens": 20, "cache_creation_input_tokens": 8, "output_tokens": 10})),
        line({"type": "user", "timestamp": "2026-09-02T02:00:01.000Z", "sessionId": "sess-a",
              "message": {"role": "user", "content": "PRIVATE SENTINEL USER"}}),
        # Streaming repeat of the same message id: component-wise maxima, one record.
        line(claude_record("2026-09-02T02:00:02.000Z", "msg_1", "claude-opus-4-1",
                           {"input_tokens": 2, "cache_read_input_tokens": 20, "cache_creation_input_tokens": 8, "output_tokens": 20})),
        line(claude_record("2026-09-02T02:00:03.000Z", "msg_synthetic", "<synthetic>", {"input_tokens": 999, "output_tokens": 999})),
        line({"type": "assistant", "timestamp": "2026-09-02T02:00:04.000Z", "sessionId": "sess-a",
              "message": {"model": "claude-opus-4-1", "usage": {"input_tokens": 999, "output_tokens": 999}}}),
        line(claude_record("2026-08-31T23:00:00.000Z", "msg_before_since", "claude-opus-4-1", {"input_tokens": 999, "output_tokens": 999})),
        line(claude_record("2026-09-02T03:15:30.500Z", "msg_2", "claude-sonnet-4",
                           {"input_tokens": 100, "cache_read_input_tokens": 0, "cache_creation_input_tokens": 0, "output_tokens": 50},
                           version="1.0.101")),
        b'{"type":"assistant","timestamp":"2026-09-02T03:16:00.000Z","message":{"id":"msg_broken"\n',
        line(claude_record("2026-09-02T03:20:00.000Z", "msg_3", "claude-sonnet-4",
                           {"input_tokens": 7, "output_tokens": 3}, session=None)),
        line(claude_record("2026-09-02T03:30:00.000Z", "msg_4", "claude-sonnet-4",
                           {"input_tokens": 1, "output_tokens": 1}, session="sess-ünicode-\U0001F600")),
        line(claude_record("2026-09-02T03:31:00.000Z", "msg_5", "claude-haiku-3-5-with-a-very-long-model-name-" + "x" * 80,
                           {"input_tokens": 1, "output_tokens": 2})),
    ], trailing_partial=b'{"type":"assistant","timestamp":"2026-09-02T04:00:00.000Z","message":{"id":"msg_partial"')
    write_lines(projects / "-Users-synthetic-project" / "sess-a" / "subagents" / "agent-1.jsonl", [
        line(claude_record("2026-09-02T02:05:00.000Z", "msg_sub", "claude-opus-4-1",
                           {"input_tokens": 3, "cache_read_input_tokens": 0, "cache_creation_input_tokens": 0, "output_tokens": 4})),
    ])

    sessions = PARITY / "codex" / "sessions" / "2026" / "09" / "02"
    limits = lambda used, minutes, reset: {"used_percent": used, "resets_at": reset, "window_minutes": minutes}
    write_lines(sessions / f"rollout-2026-09-02T01-00-00-{SESSION_MAIN}.jsonl", [
        line({"timestamp": "2026-09-02T01:00:00.000Z", "type": "session_meta",
              "payload": {"id": SESSION_MAIN, "timestamp": "2026-09-02T01:00:00.000Z", "cli_version": "0.40.0",
                          "cwd": "/private/synthetic", "originator": "codex_cli_rs"}}),
        line({"timestamp": "2026-09-02T01:00:01.000Z", "type": "turn_context", "payload": {"model": "gpt-5-codex", "cwd": "/private/synthetic"}}),
        line({"timestamp": "2026-09-02T01:00:02.000Z", "type": "response_item",
              "payload": {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "PRIVATE SENTINEL B"}]}}),
        line({"timestamp": "2026-09-02T01:00:05.000Z", "type": "event_msg", "payload": {"type": "task_started", "turn_id": TURN_MAIN}}),
        line(codex_token_count("2026-09-02T01:00:10.250Z", usage(100), usage(100),
                               {"limit_id": "codex", "limit_name": "Codex",
                                "primary": limits(20, 300, 1788314400), "secondary": limits(5.5, 10080, 1788800000)})),
        line(codex_token_count("2026-09-02T01:01:00.000Z", usage(160, cached=30, output=10, total=200), usage(60, cached=30, output=10, total=100))),
        line(codex_token_count("2026-09-02T01:02:00.000Z", usage(160, cached=30, output=10, total=200), usage(60, cached=30, output=10, total=100))),
        line(codex_token_count("2026-09-02T01:03:00.000Z", usage(40, cached=10, written=5, output=5, total=60), usage(40, cached=10, written=5, output=5, total=60),
                               {"limit_id": "codex", "limit_name": "Codex", "primary": limits(30, 300, 1788314400)})),
        line(codex_token_count(None, usage(999, total=999), usage(1, output=1, total=2))),
        line(codex_token_count("2026-09-02T01:04:00.000Z", usage(1000, cached=10, written=5, output=6, total=1021), usage(1, output=1, total=2))),
        line(codex_token_count("2026-09-02T02:10:00.000Z", usage(1100, cached=10, written=5, output=16, total=1131), usage(100, output=10, total=110),
                               {"limit_id": "codex", "limit_name": "Codex", "secondary": limits(6, 10080, 1788800000),
                                "primary": {"used_percent": 130, "resets_at": 1788314400, "window_minutes": 300}})),
        b'{"timestamp":"2026-09-02T02:10:30.000Z","type":"event_msg","payload":{"type":"token_count","info":\n',
        line(codex_token_count("2030-01-01T00:00:00.000Z", usage(5000, total=5000), usage(5000, total=5000))),
        line(codex_token_count("2026-09-02T02:11:00.000Z", usage(1100, cached=10, written=5, output=16, total=1131), {})),
    ])
    write_lines(sessions / f"rollout-2026-09-02T02-00-00-{SESSION_FORK}.jsonl", [
        line({"timestamp": "2026-09-02T02:00:00.000Z", "type": "session_meta",
              "payload": {"id": SESSION_FORK, "timestamp": "2026-09-02T02:00:00.000Z", "cwd": "/private/synthetic"}}),
        line({"timestamp": "2026-09-02T02:00:00.500Z", "type": "turn_context", "payload": {"model": "gpt-5"}}),
        # Replayed parent history precedes the child's own first task: excluded.
        line(codex_token_count("2026-09-02T01:30:00.000Z", usage(500, output=50, total=550), usage(500, output=50, total=550))),
        line({"timestamp": "2026-09-02T02:00:01.000Z", "type": "event_msg", "payload": {"type": "task_started", "turn_id": TURN_FORK_V4}}),
        line(codex_token_count("2026-09-02T02:00:10.000Z", usage(530, output=60, total=590), usage(30, output=10, total=40))),
    ])
    write_lines(PARITY / "codex" / "archived_sessions" / "rollout-old-no-meta.jsonl", [
        line({"timestamp": "2026-08-30T10:00:00.000Z", "type": "event_msg", "payload": {"type": "task_started", "turn_id": None}}),
        line(codex_token_count("2026-08-30T10:00:05.000Z", usage(10, total=10), usage(10, total=10))),
        line(codex_token_count("2026-09-03T10:00:05.000Z", usage(20, output=2, total=22), usage(10, output=2, total=12))),
    ])
    write_lines(PARITY / "codex" / "sessions" / "2026" / "09" / "03" / "empty.jsonl", [])
    (PARITY / "codex" / "sessions" / "README.txt").write_bytes(b"Not a rollout; ignored by the scan.\n")

    inbox = PARITY / "claude-statusline"
    inbox.mkdir(parents=True, exist_ok=True)
    (inbox / "2026-09-02T02.json").write_bytes(json.dumps([
        {"window_key": "five_hour", "label": "Claude · 5h", "observed_at": "2026-09-02T02:10:00Z", "used_percent": 12,
         "resets_at": "2026-09-02T05:00:00Z", "window_minutes": 300},
        {"window_key": "seven_day", "label": "Claude · weekly", "observed_at": "2026-09-02T02:10:00Z", "used_percent": 40.5,
         "resets_at": "2026-09-08T00:00:00Z", "window_minutes": 10080},
        {"window_key": "spend", "label": "Spend", "observed_at": "2026-09-02T02:10:00Z", "used_percent": 1,
         "resets_at": "2026-10-01T00:00:00Z", "window_minutes": 43200},
    ]).encode())
    (inbox / "2026-09-02T03.json").write_bytes(json.dumps([
        {"window_key": "five_hour", "label": "Claude · 5h", "observed_at": "2026-09-02T03:10:00Z", "used_percent": 15,
         "resets_at": "2026-09-02T05:00:00Z", "window_minutes": 300},
        {"window_key": "five_hour", "label": "Claude · 5h", "observed_at": "2026-09-02T03:11:00Z", "used_percent": 120,
         "resets_at": "2026-09-02T05:00:00Z", "window_minutes": 300},
        {"window_key": "five_hour", "label": "Claude · 5h", "observed_at": "2026-09-02T03:12:00Z", "used_percent": 16,
         "resets_at": "2026-09-02T03:00:00Z", "window_minutes": 300},
        {"window_key": "seven_day", "label": "Claude · weekly", "observed_at": "2026-08-01T00:00:00Z", "used_percent": 1,
         "resets_at": "2026-08-08T00:00:00Z", "window_minutes": 10080},
    ]).encode())
    (inbox / "broken.json").write_bytes(b"not json\n")
    (inbox / "missing-label.json").write_bytes(json.dumps([
        {"window_key": "five_hour", "observed_at": "2026-09-02T04:10:00Z", "used_percent": 10,
         "resets_at": "2026-09-02T05:00:00Z", "window_minutes": 300},
    ]).encode())
    (PARITY / "claude-statusline-status.json").write_bytes(json.dumps({
        "invocations": 3, "last_invocation_at": "2026-09-02T03:10:00Z", "rate_limits_present": True,
        "published_windows": ["five_hour"], "offered_windows": {}, "rate_limit_keys": ["five_hour"],
        "claude_code_version": "2.0.0", "entrypoint": "cli", "last_published_at": "2026-09-02T03:10:00Z",
    }, indent=2, sort_keys=True).encode())


# --- wire corpus ---------------------------------------------------------------

B_CLAUDE = "5d1b2c3e-4f50-4a6b-8c7d-0e1f2a3b4c5d"
B_CODEX = "6e2c3d4f-5a61-4b7c-9d8e-1f2a3b4c5d6e"
B_CURSOR = "7f3d4e5a-6b72-4c8d-ae9f-2a3b4c5d6e7f"
B_BROWSER = "8a4e5f6b-7c83-4d9e-bfa0-3b4c5d6e7f80"
SHA = lambda seed: uuid.uuid5(uuid.NAMESPACE_URL, "https://synthetic.invalid/" + seed).hex * 2
RID = lambda seed: str(uuid.uuid5(uuid.NAMESPACE_URL, "https://synthetic.invalid/record/" + seed))


def run_block(companion="companion", platform="darwin", arch="arm64"):
    return {"run_id": "9c0f1a2b-3d4e-4f50-8a6b-7c8d9e0f1a2b", "started_at": "2026-09-02T04:00:00.000Z",
            "finished_at": "2026-09-02T04:00:02.500Z",
            "companion_version": "2.0.0" if companion == "companion" else "browser-2.0.0",
            "platform": platform, "arch": arch, "settings_version": 3}


def header(adapter, channel, binding, seed, observed_at="2026-09-02T03:20:00.000Z", basis="exact", parser_version="2.0.0+v1.1.0"):
    return {"record_id": RID(seed), "binding_id": binding, "adapter": adapter, "channel": channel,
            "observed_at": observed_at, "basis": basis, "parser_version": parser_version}


def coverage(adapter, state, detail=None, **counts):
    row = {"adapter": adapter, "state": state, "detail_code": detail, "stores_discovered": 0, "files": 0, "bytes_read": 0,
           "records_emitted": 0, "malformed": 0, "rejected_by_server": 0, "duration_ms": 1,
           "cursor_state": "complete" if state in ("ok", "partial") else "unknown", "probe_requests": 0,
           "parser_version": "2.0.0+v1.1.0" if adapter.endswith("_execution") or adapter.endswith("_browser") else "0"}
    row.update(counts)
    return row


def bucket(binding, model, hour, tokens, calls=1):
    fresh, cached, written, output = tokens
    return {"binding_id": binding, "bucket": {"session_hash": SHA("session-" + model), "hour": hour, "model": model,
                                              "input_tokens": fresh, "cached_tokens": cached, "cache_write_tokens": written,
                                              "output_tokens": output, "total_tokens": fresh + cached + written + output,
                                              "calls": calls}}


def activity_request(seed="claude-msg_2", tools=None, reasoning=None, output=50):
    record = {**header("claude_execution", "local_file", B_CLAUDE, seed, observed_at="2026-09-02T03:15:30.500Z"),
              "record_type": "activity.request", "semantic_key": SHA(seed), "product": "claude_code", "surface": "cli",
              "execution_host": "local", "session_hash": SHA("sess-a"), "session_identity": "provider",
              "parent_session_hash": None, "model_requested": None, "model_actual": "claude-sonnet-4",
              "started_at": None, "ended_at": "2026-09-02T03:15:30.500Z",
              "tokens": {"input_fresh": 100, "input_cached": 0, "input_cache_write": 0, "output": output, "reasoning": reasoning},
              "tool_calls": None if tools is None else sum(t["calls"] for t in tools),
              "project_hash": None, "client_version": "1.0.101", "latency_ms": None, "outcome": "completed"}
    if tools is not None:
        record["tools"] = tools
    return record


def usage_bucket(seed="cursor-event-1"):
    return {**header("cursor_account", "provider_api", B_CURSOR, seed, basis="reported", parser_version="1"),
            "record_type": "account.usage_bucket", "report_source": "cursor_usage_events",
            "bucket_start": "2026-09-02T03:00:00.000Z", "bucket_end": "2026-09-02T03:00:01.000Z", "provider_timezone": None,
            "dimensions": {"model": "claude-sonnet-4", "product": "cursor", "client": None, "user_ref": None,
                           "workspace_ref": None, "api_key_ref": None},
            "measures": {"requests": 1, "input_tokens": 1200, "cached_tokens": 800, "cache_write_tokens": None,
                         "output_tokens": 300, "reasoning_tokens": None, "total_tokens": None},
            "provider_event_id": "evt_synthetic_000001", "provider_refreshed_at": "2026-09-02T03:19:00.000Z"}


def allowance(adapter, channel, binding, reader, meter_key, label, value, minutes, resets_at, raw, seed,
              kind="percent_used", unit="percent", capacity=None, observed_at="2026-09-02T03:20:00.000Z"):
    return {**header(adapter, channel, binding, seed, observed_at=observed_at, basis="reported"),
            "record_type": "allowance.reading", "meter_key": meter_key, "label": label, "kind": kind, "value": value,
            "unit": unit, "capacity": capacity, "window_minutes": minutes, "window_started_at": None,
            "resets_at": resets_at, "reader": reader, "raw_window_id": raw}


def money(seed="cursor-charge-1", amount="0.040000", kind="metered_charge"):
    return {**header("cursor_account", "provider_api", B_CURSOR, seed, basis="reported", parser_version="1"),
            "record_type": "money.entry", "entry_kind": kind, "amount": amount, "unit": "USD", "source_unit": "cents",
            "price_basis": "provider_reported", "period_start": "2026-09-02T03:00:00.000Z", "period_end": "2026-09-02T03:00:01.000Z",
            "reference": {"kind": "provider_event", "key": "evt_synthetic_000001"}, "sku": None, "model": "claude-sonnet-4"}


def companion_coverage():
    return [coverage("claude_execution", "ok", stores_discovered=1, files=3, bytes_read=4096, records_emitted=2),
            coverage("codex_execution", "partial", "unavailable_roots", stores_discovered=1, files=3, bytes_read=8192, malformed=1),
            coverage("claude_account", "disabled_by_setting", "mode_off"),
            coverage("codex_account", "prerequisite_missing", "executable_missing"),
            coverage("cursor_execution", "disabled_by_setting", "provider_disabled"),
            coverage("cursor_account", "disabled_by_setting", "provider_disabled"),
            coverage("anthropic_api", "disabled_by_setting", "provider_disabled"),
            coverage("openai_api", "disabled_by_setting", "provider_disabled")]


def valid_envelopes() -> dict[str, dict]:
    codex_embedded = allowance("codex_execution", "local_file", B_CODEX, "embedded", "codex:300", "Codex · 5h", 30, 300,
                               "2026-09-02T02:00:00.000Z", "primary", "codex-primary-0103", observed_at="2026-09-02T01:03:00.000Z")
    return {
        "companion-buckets-and-coverage": {"schema_version": 2, "run": run_block(),
            "buckets": [bucket(B_CLAUDE, "claude-opus-4-1", "2026-09-02T02:00:00.000Z", (5, 20, 8, 24), calls=2),
                        bucket(B_CODEX, "gpt-5-codex", "2026-09-02T01:00:00.000Z", (155, 40, 5, 15), calls=3)],
            "records": [], "coverage": companion_coverage()},
        "companion-all-record-types": {"schema_version": 2, "run": run_block(),
            "buckets": [],
            "records": [activity_request(tools=[{"name": "Read", "calls": 3}, {"name": "h:0123456789abcdef", "calls": 1}], reasoning=10),
                        usage_bucket(), codex_embedded, money()],
            "coverage": [coverage("claude_execution", "ok", records_emitted=1), coverage("cursor_account", "ok", records_emitted=2, probe_requests=2, parser_version="1")]},
        "browser-allowance-readings": {"schema_version": 2, "run": run_block("browser", "darwin", "unknown"),
            "records": [
                allowance("claude_browser", "browser_session", B_BROWSER, "web_backend", "five_hour", "5-hour allowance", 12.5, 300,
                          "2026-09-02T05:00:00.000Z", "session", "browser-five-hour"),
                allowance("claude_browser", "browser_session", B_BROWSER, "web_backend", "seven_day", "Weekly · all models", 40, 10080,
                          "2026-09-08T00:00:00.000Z", "weekly_all", "browser-seven-day"),
                allowance("claude_browser", "browser_session", B_BROWSER, "web_backend", "seven_day_claude_opus_4", "Weekly · Claude Opus 4", 3, 10080,
                          "2026-09-08T00:00:00.000Z", "weekly_scoped", "browser-seven-day-opus")],
            "coverage": [coverage("claude_browser", "ok", records_emitted=3, probe_requests=3),
                         coverage("codex_browser", "prerequisite_missing", "no_tab"),
                         coverage("cursor_browser", "disabled_by_setting", "mode_off")]},
        "minimal-coverage-only": {"schema_version": 2, "run": run_block(), "coverage": []},
        "allowance-non-percent-kinds": {"schema_version": 2, "run": run_block(),
            "records": [
                allowance("codex_account", "app_server", B_CODEX, "app_server", "codex:credits", "Codex credits", 42.25, None, None, "credits",
                          "codex-credits", kind="credits_remaining", unit="credits", capacity=100),
                allowance("cursor_account", "provider_api", B_CURSOR, "usage_summary", "cursor:requests", "Cursor requests", 180, 43200,
                          "2026-10-01T00:00:00.000Z", "requests", "cursor-requests", kind="count_remaining", unit="requests", capacity=500),
                allowance("cursor_account", "provider_api", B_CURSOR, "usage_summary", "cursor:unlimited", "Cursor unlimited", None, None, None,
                          None, "cursor-unlimited", kind="unlimited", unit=None),
                allowance("codex_account", "app_server", B_CODEX, "app_server", "codex:unavailable", "Codex allowance", None, None, None,
                          None, "codex-unavailable", kind="unavailable", unit=None)],
            "coverage": [coverage("codex_account", "ok", records_emitted=2, probe_requests=1, parser_version="1"),
                         coverage("cursor_account", "ok", records_emitted=2, probe_requests=1, parser_version="1")]},
    }


def invalid_envelopes() -> dict[str, tuple[str, bool, dict]]:
    """name -> (reason, schema_expressible, envelope)."""
    def base(records=None, buckets=None, coverage_rows=None, run=None):
        env = {"schema_version": 2, "run": run or run_block(), "coverage": coverage_rows if coverage_rows is not None else []}
        if records is not None:
            env["records"] = records
        if buckets is not None:
            env["buckets"] = buckets
        return env

    good_bucket = bucket(B_CLAUDE, "claude-opus-4-1", "2026-09-02T02:00:00.000Z", (5, 20, 8, 24), calls=2)
    bad_total = json.loads(json.dumps(good_bucket)); bad_total["bucket"]["total_tokens"] = 1
    bad_hour = json.loads(json.dumps(good_bucket)); bad_hour["bucket"]["hour"] = "2026-09-02T02:30:00.000Z"
    negative = json.loads(json.dumps(good_bucket)); negative["bucket"]["input_tokens"] = -1
    unknown_field = json.loads(json.dumps(good_bucket)); unknown_field["bucket"]["path"] = "/private/synthetic"
    empty_bucket = usage_bucket(); empty_bucket["bucket_end"] = empty_bucket["bucket_start"]
    expired = allowance("codex_execution", "local_file", B_CODEX, "embedded", "codex:300", "Codex · 5h", 30, 300,
                        "2026-09-02T00:00:00.000Z", "primary", "expired", observed_at="2026-09-02T01:03:00.000Z")
    out_of_range = allowance("codex_execution", "local_file", B_CODEX, "embedded", "codex:300", "Codex · 5h", 130, 300,
                             "2026-09-02T02:00:00.000Z", "primary", "range", observed_at="2026-09-02T01:03:00.000Z")
    future = activity_request(); future["observed_at"] = "2099-01-01T00:00:00.000Z"
    bad_type = activity_request(); bad_type["record_type"] = "activity.turn"
    bad_uuid = activity_request(); bad_uuid["record_id"] = "not-a-uuid"
    bad_stamp = activity_request(); bad_stamp["observed_at"] = "2026-09-02T03:15:30"
    missing_nullable = activity_request(); del missing_nullable["tool_calls"]
    bad_amount = money(); bad_amount["amount"] = "1.2345678"
    bad_adapter = activity_request(); bad_adapter["adapter"] = "claude_desktop"
    too_many_tools = activity_request(tools=[{"name": f"Tool{i}", "calls": 1} for i in range(51)])
    bad_version = base(); bad_version["schema_version"] = 1
    return {
        "reasoning-exceeds-output": ("reasoning_exceeds_output", False, base(records=[activity_request(reasoning=51, output=50)])),
        "empty-usage-bucket": ("empty_bucket", False, base(records=[empty_bucket])),
        "expired-allowance-reading": ("expired_reading", False, base(records=[expired])),
        "percent-out-of-range": ("percent_out_of_range", False, base(records=[out_of_range])),
        "future-observed-at": ("timestamp_in_future", False, base(records=[future])),
        "bucket-total-mismatch": ("bucket_total_mismatch", False, base(buckets=[bad_total])),
        "bucket-hour-not-boundary": ("hour_not_boundary", False, base(buckets=[bad_hour])),
        "negative-counter": ("negative_counter", True, base(buckets=[negative])),
        "unknown-field": ("unknown_field", True, base(buckets=[unknown_field])),
        "unknown-record-type": ("unknown_record_type", True, base(records=[bad_type])),
        "wrong-schema-version": ("wrong_schema_version", True, bad_version),
        "too-many-tools": ("too_many_tools", True, base(records=[too_many_tools])),
        "invalid-uuid": ("invalid_uuid", True, base(records=[bad_uuid])),
        "stamp-without-offset": ("stamp_without_offset", True, base(records=[bad_stamp])),
        "missing-nullable-field": ("missing_field", True, base(records=[missing_nullable])),
        "bad-money-amount": ("bad_amount", True, base(records=[bad_amount])),
        "unknown-adapter": ("unknown_adapter", True, base(records=[bad_adapter])),
    }


def dump(path: Path, value) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes((json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode("utf-8"))


def generate_wire() -> None:
    for sub in ("valid", "invalid"):
        if (WIRE / sub).exists():
            shutil.rmtree(WIRE / sub)
    for name, envelope in valid_envelopes().items():
        dump(WIRE / "valid" / f"{name}.json", envelope)
    for name, (reason, expressible, envelope) in invalid_envelopes().items():
        dump(WIRE / "invalid" / f"{name}.json", {"_fixture": DECLARATION, "reason": reason,
                                                   "schema_expressible": expressible, "envelope": envelope})


def manifest() -> dict:
    files = sorted(str(p.relative_to(CORPUS)).replace(os.sep, "/") for p in CORPUS.rglob("*")
                   if p.is_file() and p.name not in ("MANIFEST.json", "README.md", ".gitattributes"))
    return {"declaration": DECLARATION, "generator": "kit-board/companion/scripts/fixtures.py",
            "consumers": ["npm test (zod)", "cargo test (serde + vendored schema + parity)", "browser normalizer tests"],
            "files": files}


def generate() -> None:
    generate_parity()
    generate_wire()
    dump(CORPUS / "MANIFEST.json", manifest())


# --- expected output from collect.py -------------------------------------------

def load_collect():
    spec = importlib.util.spec_from_file_location("collect", COLLECT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def run_v1(provider: str, roots: list[Path], quota_inbox: Path | None) -> dict:
    c = load_collect()
    with tempfile.TemporaryDirectory(prefix="parity-") as temp:
        source_id = str(uuid.uuid4())
        config = {"source_id": source_id, "account_id": ACCOUNTS[provider], "provider": provider, "mode": "local",
                  "url": "https://localhost", "key": "SYNTHETIC", "roots": [str(r) for r in roots]}
        if quota_inbox is not None:
            config["quota_inbox"] = str(quota_inbox)
        config_path = Path(temp) / "connection.json"
        config_path.write_text(json.dumps(config))
        result = subprocess.run([sys.executable, str(COLLECT), "--config", str(config_path), "--since", SINCE, "--dry-run"],
                                capture_output=True, text=True, check=True)
        output = json.loads(result.stdout.strip().splitlines()[-1])
        db = c.open_state(Path(temp) / f"{source_id}.sqlite3")
        buckets = list(c.bucket_rows(db))
        events = [dict(row) for row in db.execute(
            "SELECT id, session, hour, model, input_tokens, cached_tokens, cache_write_tokens, output_tokens FROM events ORDER BY id")]
        quotas = sorted((json.loads(row["payload"]) for row in db.execute("SELECT payload FROM quotas")),
                        key=lambda q: (q["window_key"], q["observed_at"]))
        files = db.execute("SELECT count(*) FROM files").fetchone()[0]
        db.close()
    cov = output["coverage"]
    return {
        "coverage": {k: cov[k] for k in ("files", "bytes_read", "malformed_lines", "unavailable_roots")},
        "collector_version": cov["collector_version"],
        "dry_run": {"buckets": output["buckets"], "quotas": output["quotas"]},
        "checkpointed_files": files,
        "buckets": buckets,
        "bucket_digests": [{"key": c.digest([b["session_hash"], b["hour"], b["model"]]), "hash": c.digest(b)} for b in buckets],
        "events": events,
        "quotas": quotas,
    }


def expected() -> dict:
    return {
        "_fixture": DECLARATION,
        "since": SINCE,
        "accounts": ACCOUNTS,
        "claude": run_v1("claude", [PARITY / "claude" / "projects"], PARITY / "claude-statusline"),
        "codex": run_v1("codex", [PARITY / "codex" / "sessions", PARITY / "codex" / "archived_sessions"], None),
    }


def check() -> int:
    problems = []
    current = expected()
    committed = json.loads((PARITY / "expected.json").read_bytes()) if (PARITY / "expected.json").exists() else None
    if committed != current:
        problems.append("parity/expected.json is not what collect.py produces; run `python3 scripts/fixtures.py expected`")
    if json.loads((CORPUS / "MANIFEST.json").read_bytes()) != manifest():
        problems.append("MANIFEST.json is stale; run `python3 scripts/fixtures.py generate`")
    for name, envelope in valid_envelopes().items():
        path = WIRE / "valid" / f"{name}.json"
        if not path.exists() or json.loads(path.read_bytes()) != envelope:
            problems.append(f"wire/valid/{name}.json is stale")
    for name, (reason, expressible, envelope) in invalid_envelopes().items():
        path = WIRE / "invalid" / f"{name}.json"
        if not path.exists() or json.loads(path.read_bytes()).get("envelope") != envelope:
            problems.append(f"wire/invalid/{name}.json is stale")
    for problem in problems:
        print(problem, file=sys.stderr)
    return 1 if problems else 0


def main(argv: list[str]) -> int:
    command = argv[1] if len(argv) > 1 else "check"
    if command == "generate":
        generate()
        print(f"wrote corpus under {CORPUS}")
        return 0
    if command == "expected":
        dump(PARITY / "expected.json", expected())
        dump(CORPUS / "MANIFEST.json", manifest())
        print(f"wrote {PARITY / 'expected.json'}")
        return 0
    if command == "check":
        return check()
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
