//! The side-record parity corpus (`tests/fixtures/side-records.json`, generated by
//! `tests/fixtures/side_records.py`), which `kit-board/tests/usage-contract-side-records.test.ts`
//! feeds to zod as well (tests R1, R2 and C1): every valid record deserializes, validates,
//! round-trips and passes the vendored schema; every invalid one is rejected by the types and,
//! when `schema_expressible`, by the schema alone; every normalization pair agrees.

use std::fs;
use std::path::PathBuf;
use std::str::FromStr;

use jiff::Timestamp;
use observatory_contract::stable_json::content_hash;
use observatory_contract::{
    Envelope, LabelKey, LabelKind, LabelText, MembershipResolution, ProjectName, Record, RecordType,
    SCHEMA_JSON, UNTITLED_PROJECT, UsageResponse, is_normalized_display_text, normalize_display_text,
};
use serde_json::{Value, json};

fn corpus() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/side-records.json");
    serde_json::from_str(&fs::read_to_string(path).unwrap()).unwrap()
}

fn envelope(record: &Value) -> Value {
    json!({
        "schema_version": 2,
        "run": {
            "run_id": "33333333-3333-4333-8333-333333333333",
            "started_at": "2026-09-02T03:19:00.000Z",
            "finished_at": "2026-09-02T03:21:00.000Z",
            "companion_version": "2.2.0",
            "platform": "linux",
            "arch": "amd64",
            "settings_version": 1
        },
        "buckets": [],
        "records": [record],
        "coverage": []
    })
}

fn validator() -> jsonschema::Validator {
    let schema: Value = serde_json::from_str(SCHEMA_JSON).unwrap();
    jsonschema::validator_for(&schema).unwrap()
}

#[test]
fn valid_side_records_parse_validate_round_trip_and_pass_the_schema() {
    let corpus = corpus();
    let validator = validator();
    let now = Timestamp::now();
    let valid = corpus["valid"].as_array().unwrap();
    assert!(valid.len() >= 20);
    let mut seen = Vec::new();
    for case in valid {
        let name = case["name"].as_str().unwrap();
        let body = envelope(&case["record"]);
        if let Err(error) = validator.validate(&body) {
            panic!("{name}: schema rejects a valid record: {error}");
        }
        let text = body.to_string();
        let parsed = Envelope::parse(&text, now).unwrap_or_else(|error| panic!("{name}: {error}"));
        let record = &parsed.records[0];
        assert!(record.is_side(), "{name}");
        assert_eq!(record.channel(), None, "{name}: side records have no channel");
        seen.push(record.record_type());
        let produced: Value = serde_json::from_str(&parsed.to_json().unwrap()).unwrap();
        assert_eq!(produced, body, "{name}: round trip changed the record");
    }
    for record_type in RecordType::SIDE {
        assert!(seen.contains(record_type), "{record_type} has no valid example");
    }
}

#[test]
fn invalid_side_records_are_rejected_with_their_labeled_reason() {
    let corpus = corpus();
    let validator = validator();
    let now = Timestamp::now();
    let invalid = corpus["invalid"].as_array().unwrap();
    assert!(invalid.len() >= 40);
    for case in invalid {
        let reason = case["reason"].as_str().unwrap();
        let expressible = case["schema_expressible"].as_bool().unwrap();
        let body = envelope(&case["record"]);
        assert!(
            Envelope::parse(&body.to_string(), now).is_err(),
            "{reason}: the types accepted an invalid record"
        );
        let schema_accepts = validator.is_valid(&body);
        if expressible {
            assert!(!schema_accepts, "{reason}: the schema accepted a record it should reject");
        } else {
            assert!(
                schema_accepts,
                "{reason}: labeled as not expressible in JSON Schema, yet the schema rejects it"
            );
        }
    }
}

#[test]
fn normalization_matches_the_shared_pairs() {
    let corpus = corpus();
    for case in corpus["normalization"].as_array().unwrap() {
        let raw = case["raw"].as_str().unwrap();
        let max = usize::try_from(case["max"].as_u64().unwrap()).unwrap();
        let normalized = normalize_display_text(raw, max);
        assert_eq!(normalized.text, case["text"].as_str().unwrap(), "{raw:?}");
        assert_eq!(normalized.truncated, case["truncated"].as_bool().unwrap(), "{raw:?}");
        assert!(normalized.text.is_empty() || is_normalized_display_text(&normalized.text, max), "{raw:?}");
    }
}

#[test]
fn display_text_is_built_only_through_normalization() {
    let (label, truncated) = LabelText::normalize("  mcp tool\u{2028} ");
    assert_eq!(label.unwrap().as_str(), "mcp tool");
    assert!(!truncated);

    let (empty, truncated) = LabelText::normalize("\u{feff} \u{85}\u{2029}");
    assert!(empty.is_none(), "an empty label is not produced");
    assert!(!truncated);

    let long = format!("{}{}", "é".repeat(199), "日本");
    let (cut, truncated) = LabelText::normalize(&long);
    let cut = cut.unwrap();
    assert!(truncated);
    assert_eq!(cut.as_str().chars().count(), 200);
    assert!(cut.as_str().ends_with("é日"), "cut at a character boundary");

    // Truncation lands on a space, which the second trim removes.
    let (spaced, truncated) = ProjectName::normalize(&format!("{} tail", "n".repeat(79)));
    assert!(truncated);
    assert_eq!(spaced.unwrap().as_str(), "n".repeat(79));

    let (untitled, truncated) = ProjectName::project_name(" \u{200b}\u{00ad} ");
    assert_eq!(untitled.as_str(), UNTITLED_PROJECT);
    assert!(!truncated);
    let (named, _) = ProjectName::project_name("\u{feff}Sample\u{2028}Project ");
    assert_eq!(named.as_str(), "SampleProject");

    assert!(LabelText::from_str(" padded").is_err());
    assert!(LabelText::from_str("a\u{2029}b").is_err());
    assert!(LabelText::from_str(&"x".repeat(201)).is_err());
    assert!(LabelText::from_str(&"😀".repeat(200)).is_ok(), "the limit counts characters, not UTF-16 units");
    assert!(ProjectName::from_str(&"p".repeat(81)).is_err());
}

#[test]
fn label_keys_and_kinds_agree() {
    assert!(LabelKey::from_str("h:0123456789abcdef").unwrap().is_hashed_name());
    assert!(!LabelKey::from_str(&"a".repeat(64)).unwrap().is_hashed_name());
    for bad in ["h:0123", "h:0123456789ABCDEF", "PowerShell", "", &"a".repeat(63)] {
        assert!(LabelKey::from_str(bad).is_err(), "{bad}");
    }
    for kind in LabelKind::ALL {
        assert_eq!(kind.allows_role(), matches!(kind, LabelKind::Agent | LabelKind::SessionAgent), "{kind}");
        assert_eq!(kind.allows_parent_key(), *kind == LabelKind::SessionAgent, "{kind}");
    }
    let named: Vec<_> = MembershipResolution::ALL
        .iter()
        .filter(|resolution| resolution.names_project())
        .map(|r| r.as_str())
        .collect();
    assert_eq!(named, ["app_assignment", "inherited", "root_prefix", "worktree_root_prefix"]);
}

#[test]
fn side_record_identity_ignores_the_carrier() {
    let corpus = corpus();
    let first: Record = serde_json::from_value(corpus["valid"][0]["record"].clone()).unwrap();
    let mut moved = corpus["valid"][0]["record"].clone();
    moved["record_id"] = json!("44444444-4444-4444-8444-444444444444");
    moved["binding_id"] = json!("55555555-5555-4555-8555-555555555555");
    moved["observed_at"] = json!("2026-09-02T04:00:00.000Z");
    let moved: Record = serde_json::from_value(moved).unwrap();
    assert_eq!(content_hash(&first).unwrap(), content_hash(&moved).unwrap());
    assert_eq!(first.semantic_key(), moved.semantic_key());
    assert_eq!(first.semantic_key(), "tool:h:0123456789abcdef");
}

#[test]
fn usage_response_reads_deferred_ids_only_when_present() {
    let old = json!({
        "ok": true, "schema_version": 2, "run_id": "33333333-3333-4333-8333-333333333333",
        "accepted": { "buckets": 0, "records": 1 }, "duplicates": 0, "rejected": []
    });
    let parsed: UsageResponse = serde_json::from_value(old.clone()).unwrap();
    assert!(parsed.deferred_record_ids.is_empty());
    assert_eq!(serde_json::to_value(&parsed).unwrap(), old, "an old response keeps its bytes");

    let mut deferred = old;
    deferred["deferred_record_ids"] = json!(["11111111-1111-4111-8111-000000000001"]);
    let parsed: UsageResponse = serde_json::from_value(deferred).unwrap();
    assert_eq!(parsed.deferred_record_ids.len(), 1);
}
