import type { KitManifest } from './types';

export const usageKit = {
  id: 'usage',
  title: 'AI usage',
  summary: 'The companion and the browser quota bridge collect token, request and allowance readings on each machine; the monthly exporters publish one usage envelope per machine and month.',
  directory: 'kit-board',
  extracted: false,
  page: { path: '/usage', empty: 'Monthly usage reports will appear after the first upload.' },
  reports: [{ kind: 'usage', contract: 'usage-v2', enforcement: 'enforce' }],
  producers: ['usage'],
  schedules: [
    { name: 'Monthly AI usage', kind: 'usage', owner: 'Codex + Claude · each computer', cadence: 'Codex: 1st · 9:00 AM. Claude catch-up: 2nd–5th · 9:15 AM', source: 'monthly-ai-usage', connected: true },
  ],
  endpoints: [
    { method: 'POST', path: '/api/v1/usage', auth: 'install', contract: 'usage-v2', summary: 'Companion usage upload: request ledger, token buckets and allowance readings.' },
    { method: 'POST', path: '/api/v1/companion/pair', auth: 'pairing-code', summary: 'Exchanges a one-time pairing code for an install id and key.' },
    { method: 'GET', path: '/api/v1/companion/config', auth: 'install', summary: "The install's effective config document, with an ETag." },
    { method: 'PUT', path: '/api/v1/companion/settings', auth: 'install', summary: "Replaces the install's settings override." },
    { method: 'POST', path: '/api/v1/companion/bindings', auth: 'install', summary: 'Creates a binding between the install and an account.' },
    { method: 'POST', path: '/api/v1/companion/bindings/:id/identity', auth: 'install', summary: "Re-confirms a binding's identity after the board approved it." },
    { method: 'POST', path: '/api/v1/companion/capabilities', auth: 'install', summary: 'Records what this companion build can do.' },
    { method: 'POST', path: '/api/v1/telemetry', auth: 'telemetry', summary: 'Allowance readings from the browser quota bridge.' },
    { method: 'POST', path: '/api/reports', auth: 'producer', scope: 'usage', summary: 'Monthly usage envelope from the monthly-ai-usage exporters.' },
    { method: 'GET', path: '/api/reports', auth: 'session', summary: 'Monthly usage history.' },
    { method: 'GET', path: '/api/reset-feeds', auth: 'session', summary: 'Reset feed health.' },
    { method: 'POST', path: '/api/reset-feeds', auth: 'telemetry-or-session', summary: 'Refreshes the public reset feeds, from a local source or the settings page.' },
    { method: 'GET', path: '/api/internal/sync-legacy-usage', auth: 'cron', summary: 'Copies reports from the old usage site.' },
    { method: 'GET', path: '/api/internal/sync-reset-feeds', auth: 'cron', summary: 'Daily refresh of the public reset feeds.' },
    { method: 'GET', path: '/api/internal/sync-companion-release', auth: 'cron', summary: 'Records the newest companion release.' },
    { method: 'GET', path: '/api/usage-v2', auth: 'session', summary: 'Installs, bindings, coverage, settings and current allowance readings.' },
    { method: 'GET', path: '/api/usage-query', auth: 'session', summary: 'Filtered usage read for Tokens.' },
    { method: 'GET', path: '/api/usage-live', auth: 'session', summary: 'Telemetry dashboard and allowance calibrations.' },
    { method: 'GET', path: '/api/usage-projects', auth: 'session', summary: 'Projects the Tokens filter offers.' },
    { method: 'PUT', path: '/api/usage-projects', auth: 'session', summary: 'Retired; answers 405.' },
    { method: 'GET', path: '/api/usage-projects/stats', auth: 'session', summary: 'Per project counts for Settings > Projects.' },
    { method: 'GET', path: '/api/usage-report-subjects', auth: 'session', summary: 'Monthly report subjects and their accounts.' },
    { method: 'PUT', path: '/api/usage-report-subjects', auth: 'session', summary: 'Maps a monthly report subject to an account.' },
    { method: 'GET', path: '/api/usage-knowledge-sources', auth: 'session', summary: 'Knowledge sources the usage views count.' },
    { method: 'PUT', path: '/api/usage-knowledge-sources', auth: 'session', summary: 'Replaces the knowledge source list.' },
    { method: 'POST', path: '/api/usage-calibrations', auth: 'session', summary: 'Records an allowance calibration.' },
    { method: 'DELETE', path: '/api/usage-calibrations', auth: 'session', summary: 'Revokes an allowance calibration.' },
    { method: 'GET', path: '/api/usage-connections', auth: 'session', summary: 'Browser connections and their last contact.' },
    { method: 'POST', path: '/api/usage-connections', auth: 'session', summary: 'Retired; answers 410.' },
    { method: 'PATCH', path: '/api/usage-connections', auth: 'session', summary: 'Pauses or resumes a browser connection.' },
    { method: 'DELETE', path: '/api/usage-connections', auth: 'session', summary: 'Disables a connection.' },
    { method: 'GET', path: '/api/collection-settings', auth: 'session', summary: 'The collection settings document.' },
    { method: 'PUT', path: '/api/collection-settings', auth: 'session', summary: 'Replaces the collection settings document.' },
    { method: 'POST', path: '/api/companion-installs', auth: 'session', summary: 'Issues a one-time pairing code.' },
    { method: 'PATCH', path: '/api/companion-installs', auth: 'session', summary: 'Pauses, resumes or overrides an install or binding.' },
    { method: 'DELETE', path: '/api/companion-installs', auth: 'session', summary: 'Disables an install.' },
    { method: 'GET', path: '/api/collector-download', auth: 'session', summary: 'Retired; answers 410.' },
  ],
  downloads: [
    { label: 'Usage upload schema', path: 'kit-board/lib/generated/usage-v2.schema.json', summary: 'JSON Schema for the companion usage upload.' },
    { label: 'Browser quota bridge', path: 'kit-board/browser', summary: 'Unpacked browser extension that uploads allowance readings.' },
    { label: 'Companion source', path: 'kit-board/companion', summary: 'The observatory companion. Install a release with Homebrew or Scoop rather than building it.' },
  ],
} as const satisfies KitManifest;
