import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  LABEL_MAX_CHARS, PROJECT_NAME_MAX_CHARS, contentSubject, isSideRecord, labelText, normalizeDisplayText, parseUsageEnvelope,
  projectName, sideRecordTypes, usageRecordSchema, usageResponseSchema,
} from '../lib/usage-contract';
import { companionCapabilitiesSchema } from '../lib/companion-capabilities';

/**
 * The side-record parity corpus the companion's `cargo test -p observatory-contract` reads too
 * (tests R1, R2 and C1). It lives with the Rust contract crate and is generated by
 * `side_records.py` beside it.
 */
type Corpus = {
  valid: { name: string; record: Record<string, unknown> }[];
  invalid: { reason: string; schema_expressible: boolean; record: Record<string, unknown> }[];
  normalization: { raw: string; max: number; text: string; truncated: boolean }[];
};
const corpus = JSON.parse(readFileSync(join(import.meta.dirname, '..', 'companion', 'crates', 'observatory-contract',
  'tests', 'fixtures', 'side-records.json'), 'utf8')) as Corpus;

const envelope = (records: unknown[]) => ({
  schema_version: 2,
  run: { run_id: '33333333-3333-4333-8333-333333333333', started_at: '2026-09-02T03:19:00.000Z',
    finished_at: '2026-09-02T03:21:00.000Z', companion_version: '2.2.0', platform: 'linux', arch: 'amd64', settings_version: 1 },
  records, coverage: [],
});

test('every valid side record parses and keeps its shape', () => {
  assert.ok(corpus.valid.length >= 20);
  const seen = new Set<string>();
  for (const { name, record } of corpus.valid) {
    const parsed = usageRecordSchema.safeParse(record);
    assert.ok(parsed.success, `${name}: ${parsed.success ? '' : JSON.stringify(parsed.error.issues)}`);
    assert.deepEqual(parsed.data, record, name);
    assert.ok(isSideRecord(parsed.data), name);
    seen.add(parsed.data.record_type);
  }
  assert.deepEqual([...seen].sort(), [...sideRecordTypes].sort(), 'every side type has a valid example');
});

test('every invalid side record is rejected with its labeled reason', () => {
  assert.ok(corpus.invalid.length >= 40);
  for (const { reason, record } of corpus.invalid) {
    assert.equal(usageRecordSchema.safeParse(record).success, false, `${reason} was accepted`);
  }
});

test('an invalid side record is rejected alone, never the envelope', () => {
  const good = corpus.valid.map(entry => entry.record);
  const bad = corpus.invalid.find(entry => entry.reason === 'membership projectless with a project')!.record;
  const { envelope: parsed, invalid } = parseUsageEnvelope(envelope([...good, bad]));
  assert.equal(parsed.records.length, good.length);
  assert.deepEqual(invalid, [{ record_id: bad.record_id, reason: 'invalid' }]);
});

test('normalization matches the shared pairs, and its output always validates', () => {
  for (const { raw, max, text, truncated } of corpus.normalization) {
    const normalized = normalizeDisplayText(raw, max);
    assert.deepEqual(normalized, { text, truncated }, JSON.stringify(raw));
    if (text) assert.equal(labelText(max).safeParse(text).success, true, JSON.stringify(text));
  }
});

test('display text limits count characters, not UTF-16 units', () => {
  const astral = String.fromCodePoint(0x1f600);
  assert.equal(labelText(LABEL_MAX_CHARS).safeParse(astral.repeat(200)).success, true);
  assert.equal(labelText(LABEL_MAX_CHARS).safeParse(astral.repeat(201)).success, false);
  assert.equal(projectName.safeParse('p'.repeat(PROJECT_NAME_MAX_CHARS)).success, true);
  assert.equal(projectName.safeParse('p'.repeat(PROJECT_NAME_MAX_CHARS + 1)).success, false);
});

/**
 * Test C2's in-process half: whatever zod accepts also satisfies the DB CHECK
 * `char_length BETWEEN 1 AND max AND s = btrim(s) AND s !~ '[[:cntrl:]]'`. `btrim` removes
 * only U+0020, which zod's trim rule covers; `[[:cntrl:]]` is at most Cc (plus, under some
 * libc locales, Zl, Zp and Cf), all of which zod forbids. The database half of C2 (ICU and libc
 * collations) belongs with the migration tests under `npm run test:db`.
 */
test('accepted display text satisfies the database checks', () => {
  const samples: string[] = [];
  let seed = 7;
  const next = () => (seed = (seed * 1_103_515_245 + 12_345) % 2 ** 31);
  const planes = [0x20, 0x7f, 0xa0, 0x2000, 0x2028, 0xfeff, 0x3000, 0x1f600, 0x0600, 0xe0001];
  for (let i = 0; i < 4000; i++) {
    const length = 1 + (next() % 12);
    let text = '';
    for (let j = 0; j < length; j++) {
      const base = planes[next() % planes.length];
      text += String.fromCodePoint(Math.max(0, base - 4 + (next() % 16)));
    }
    samples.push(text, normalizeDisplayText(text, LABEL_MAX_CHARS).text);
  }
  let accepted = 0;
  for (const text of samples) {
    if (!labelText(LABEL_MAX_CHARS).safeParse(text).success) continue;
    accepted++;
    const chars = Array.from(text).length;
    assert.ok(chars >= 1 && chars <= LABEL_MAX_CHARS, JSON.stringify(text));
    assert.equal(text, text.replace(/^ +| +$/g, ''), `btrim: ${JSON.stringify(text)}`);
    assert.equal(/[\p{Cc}\p{Cf}\p{Zl}\p{Zp}]/u.test(text), false, `cntrl: ${JSON.stringify(text)}`);
  }
  assert.ok(accepted > 1000, `the sample exercises acceptance (${accepted})`);
});

test('side records hash without their observation identity or carrier', () => {
  const record = usageRecordSchema.parse(corpus.valid[0].record);
  const moved = usageRecordSchema.parse({ ...corpus.valid[0].record, record_id: '44444444-4444-4444-8444-444444444444',
    binding_id: '55555555-5555-4555-8555-555555555555', observed_at: '2026-09-02T04:00:00.000Z', parser_version: '2.2.1' });
  assert.deepEqual(contentSubject(record), contentSubject(moved));
  for (const key of ['record_id', 'binding_id', 'observed_at', 'parser_version']) assert.equal(key in contentSubject(record), false, key);
});

test('the usage response carries deferred record ids only when there are some', () => {
  const old = { ok: true, schema_version: 2, run_id: '33333333-3333-4333-8333-333333333333',
    accepted: { buckets: 0, records: 1 }, duplicates: 0, rejected: [] };
  assert.equal(usageResponseSchema.safeParse(old).success, true);
  assert.equal(usageResponseSchema.safeParse({ ...old, deferred_record_ids: ['11111111-1111-4111-8111-000000000001'] }).success, true);
  assert.equal(usageResponseSchema.safeParse({ ...old, deferred_record_ids: [] }).success, false, 'omitted when empty');
});

test('capabilities accept the labels feature and documents without it', () => {
  const corpusDir = join(import.meta.dirname, 'fixtures', 'usage-v2', 'capabilities', 'valid');
  const document = JSON.parse(readFileSync(join(corpusDir, 'default-build.json'), 'utf8')) as { features: Record<string, unknown> };
  assert.equal('labels' in document.features, false);
  assert.equal(companionCapabilitiesSchema.safeParse(document).success, true);
  const labeled = { ...document, features: { ...document.features, labels: true } };
  assert.equal(companionCapabilitiesSchema.parse(labeled).features.labels, true);
  assert.equal(companionCapabilitiesSchema.safeParse({ ...document, features: { ...document.features, labels: 'yes' } }).success, false);
});
